spring:
  datasource:
    url: jdbc:tc:postgresql:13.3:///test_database
    username: user
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: true
    url: jdbc:tc:postgresql:13.3:///test_database
    user: user
    password: password