version: "3"
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/crmit -schemas=public -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ../../../../db-migration/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres
    ports:
      [ "5433:5432" ]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "crmit"
