spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    url: jdbc:postgresql://localhost:5432/crm
    user: postgres
    password: postgres

server:
  servlet:
    context-path: /api

jwt:
  secret: "tempToken"
  expiration:
    token:
      time: 1000
    refreshToken:
      time: 600

crm:
  properties:
    vin:
      length: 17

email:
  user:
    name: "motomo@o2.pl"
    password: "MotoYYGvcpo96%"
  host:
    name: "poczta.o2.pl"
  smtp:
    port: 465
  ssl:
    connect: true
  endpoint:
    path: "http://localhost:8080/api/account/activate"
